apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-external-secrets-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: kubernetes-external-secrets-service-account
  namespace: kubernetes-external-secrets
roleRef:
  kind: ClusterRole
  name: kubernetes-external-secrets-cluster-role
  apiGroup: rbac.authorization.k8s.io
